apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: spartakus
    kustomize.component: spartakus
  name: spartakus
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: spartakus
    kustomize.component: spartakus
  name: spartakus
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: spartakus
    kustomize.component: spartakus
  name: spartakus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spartakus
subjects:
- kind: ServiceAccount
  name: spartakus
  namespace: kubeflow
---
apiVersion: v1
data:
  usageId: <randomly-generated-id>
kind: ConfigMap
metadata:
  labels:
    kustomize.component: spartakus
  name: spartakus-parameters
  namespace: kubeflow
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: spartakus
    kustomize.component: spartakus
  name: spartakus-volunteer
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      kustomize.component: spartakus
  template:
    metadata:
      labels:
        app: spartakus-volunteer
        kustomize.component: spartakus
    spec:
      containers:
      - args:
        - volunteer
        - --cluster-id=<randomly-generated-id>
        - --database=https://stats-collector.kubeflow.org
        image: registry.cn-shenzhen.aliyuncs.com/shikanon/google_containers.spartakus-amd64:v1.1.0
        name: volunteer
      serviceAccountName: spartakus
