apiVersion: v1
kind: Service
metadata:
  labels:
    app: katib
    component: suggestion-bayesianoptimization
  name: katib-suggestion-bayesianoptimization
  namespace: kubeflow
spec:
  ports:
  - name: api
    port: 6789
    protocol: TCP
  selector:
    app: katib
    component: suggestion-bayesianoptimization
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: katib
    component: suggestion-grid
  name: katib-suggestion-grid
  namespace: kubeflow
spec:
  ports:
  - name: api
    port: 6789
    protocol: TCP
  selector:
    app: katib
    component: suggestion-grid
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: katib
    component: suggestion-hyperband
  name: katib-suggestion-hyperband
  namespace: kubeflow
spec:
  ports:
  - name: api
    port: 6789
    protocol: TCP
  selector:
    app: katib
    component: suggestion-hyperband
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: katib
    component: suggestion-nasrl
  name: katib-suggestion-nasrl
  namespace: kubeflow
spec:
  ports:
  - name: api
    port: 6789
    protocol: TCP
  selector:
    app: katib
    component: suggestion-nasrl
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: katib
    component: suggestion-random
  name: katib-suggestion-random
  namespace: kubeflow
spec:
  ports:
  - name: api
    port: 6789
    protocol: TCP
  selector:
    app: katib
    component: suggestion-random
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: katib
    component: suggestion-bayesianoptimization
  name: katib-suggestion-bayesianoptimization
  namespace: kubeflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: katib
        component: suggestion-bayesianoptimization
      name: katib-suggestion-bayesianoptimization
    spec:
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/shikanon/kubeflow-images-public.katib.suggestion-bayesianoptimization:v0.6.0-rc.0
        imagePullPolicy: IfNotPresent
        name: katib-suggestion-bayesianoptimization
        ports:
        - containerPort: 6789
          name: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: katib
    component: suggestion-grid
  name: katib-suggestion-grid
  namespace: kubeflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: katib
        component: suggestion-grid
      name: katib-suggestion-grid
    spec:
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/shikanon/kubeflow-images-public.katib.v1alpha2.suggestion-grid:v0.6.0-rc.0
        imagePullPolicy: IfNotPresent
        name: katib-suggestion-grid
        ports:
        - containerPort: 6789
          name: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: katib
    component: suggestion-hyperband
  name: katib-suggestion-hyperband
  namespace: kubeflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: katib
        component: suggestion-hyperband
      name: katib-suggestion-hyperband
    spec:
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/shikanon/kubeflow-images-public.katib.v1alpha2.suggestion-hyperband:v0.6.0-rc.0
        imagePullPolicy: IfNotPresent
        name: katib-suggestion-hyperband
        ports:
        - containerPort: 6789
          name: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: katib
    component: suggestion-nasrl
  name: katib-suggestion-nasrl
  namespace: kubeflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: katib
        component: suggestion-nasrl
      name: katib-suggestion-nasrl
    spec:
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/shikanon/kubeflow-images-public.katib.v1alpha2.suggestion-nasrl:v0.6.0-rc.0
        name: katib-suggestion-nasrl
        ports:
        - containerPort: 6789
          name: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: katib
    component: suggestion-random
  name: katib-suggestion-random
  namespace: kubeflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: katib
        component: suggestion-random
      name: katib-suggestion-random
    spec:
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/shikanon/kubeflow-images-public.katib.v1alpha2.suggestion-random:v0.6.0-rc.0
        imagePullPolicy: IfNotPresent
        name: katib-suggestion-random
        ports:
        - containerPort: 6789
          name: api
